import type { TrainApiResponse } from '@/app/types/train.types';

export const MOCK_TRAIN_DATA: Record<string, TrainApiResponse> = {
  '12618': {
    train: {
      trainNumber: '12618',
      trainName: 'Mangala Lakshadweep Express (PT)',
      hindiName: '',
      type: 'SuperFast',
      zone: 'SR/Southern',
      sourceStationCode: 'NZM',
      sourceStationName: 'Hazrat Nizamuddin',
      destinationStationCode: 'ERS',
      destinationStationName: 'Ernakulam Jn',
      runningDaysBitmap: 127,
      runningDays: {
        days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        allDays: true,
        isStartingToday: true,
      },
      returnTrainNumber: '12617',
      travelTimeMinutes: 2940,
      totalHalts: 41,
      distanceKm: 2761,
      avgSpeedKmph: 56.35,
      rakeDetails: 'LHB',
      otherDetails: '',
      scrapedAt: Date.now(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    route: [
      {
        id: 1,
        sequence: 1,
        stationCode: 'NZM',
        stationName: 'Hazrat Nizamuddin',
        isHalt: 1,
        scheduledArrival: 0,
        scheduledDeparture: 335,
        haltDurationMinutes: 0,
        platform: '7',
        day: 1,
        distanceFromSourceKm: 0,
        speedOnSectionKmph: 0,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: 347,
        arrivalDelaySeconds: null,
        departureDelaySeconds: 720,
        livePlatform: '7',
        liveDistanceKm: 0,
      },
      {
        id: 2,
        sequence: 2,
        stationCode: 'MTJ',
        stationName: 'Mathura Jn',
        isHalt: 1,
        scheduledArrival: 505,
        scheduledDeparture: 510,
        haltDurationMinutes: 5,
        platform: '4',
        day: 1,
        distanceFromSourceKm: 145,
        speedOnSectionKmph: 110,
        trackTypeId: 1,
        actualArrivalTime: 518,
        actualDepartureTime: 523,
        arrivalDelaySeconds: 780,
        departureDelaySeconds: 780,
        livePlatform: '4',
        liveDistanceKm: 145,
      },
      {
        id: 3,
        sequence: 3,
        stationCode: 'BPL',
        stationName: 'Bhopal Jn',
        isHalt: 1,
        scheduledArrival: 1105,
        scheduledDeparture: 1115,
        haltDurationMinutes: 10,
        platform: '2',
        day: 1,
        distanceFromSourceKm: 705,
        speedOnSectionKmph: 95,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
      {
        id: 4,
        sequence: 4,
        stationCode: 'NGP',
        stationName: 'Nagpur',
        isHalt: 1,
        scheduledArrival: 1610,
        scheduledDeparture: 1620,
        haltDurationMinutes: 10,
        platform: '3',
        day: 1,
        distanceFromSourceKm: 1238,
        speedOnSectionKmph: 100,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
      {
        id: 5,
        sequence: 5,
        stationCode: 'ERS',
        stationName: 'Ernakulam Jn',
        isHalt: 1,
        scheduledArrival: 215,
        scheduledDeparture: 0,
        haltDurationMinutes: 0,
        platform: '1',
        day: 3,
        distanceFromSourceKm: 2761,
        speedOnSectionKmph: 0,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
    ],
    liveData: {
      trainNumber: '12618',
      trainName: 'Mangala Lakshadweep Express (PT)',
      journeyDate: '2026-01-13',
      lastUpdatedAt: new Date().toISOString(),
      currentLocation: {
        latitude: 21.31185,
        longitude: 76.16899,
        stationCode: 'MTJ',
        sequence: 2,
        status: 'DEPARTED',
        distanceFromOriginKm: 145,
        distanceFromLastStationKm: 12.5,
      },
      overallDelayMinutes: 12,
      dataSource: 'MOCK',
      route: [
        {
          sequence: 1,
          stationCode: 'NZM',
          scheduledArrival: 0,
          scheduledDeparture: 335,
          actualArrival: null,
          actualDeparture: 347,
          delayArrivalMinutes: null,
          delayDepartureMinutes: 12,
          platform: '7',
          distanceFromOriginKm: 0,
        },
        {
          sequence: 2,
          stationCode: 'MTJ',
          scheduledArrival: 505,
          scheduledDeparture: 510,
          actualArrival: 518,
          actualDeparture: 523,
          delayArrivalMinutes: 13,
          delayDepartureMinutes: 13,
          platform: '4',
          distanceFromOriginKm: 145,
        },
      ],
      exceptionInfo: null,
    },
    metadata: {
      hasLiveData: true,
      lastStaticUpdate: new Date().toISOString(),
      lastLiveUpdate: new Date().toISOString(),
      canRefreshLive: true,
      journeyStatus: {
        status: 'IN_PROGRESS',
        journeyDate: '2026-01-13',
        canFetchLiveData: true,
        startTime: new Date().toISOString(),
        endTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      },
    },
  },
  '12301': {
    train: {
      trainNumber: '12301',
      trainName: 'Howrah Rajdhani Express',
      hindiName: 'हावड़ा राजधानी एक्सप्रेस',
      type: 'Rajdhani',
      zone: 'ER/Eastern',
      sourceStationCode: 'NDLS',
      sourceStationName: 'New Delhi',
      destinationStationCode: 'HWH',
      destinationStationName: 'Howrah Jn',
      runningDaysBitmap: 127,
      runningDays: {
        days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        allDays: true,
        isStartingToday: true,
      },
      returnTrainNumber: '12302',
      travelTimeMinutes: 1025,
      totalHalts: 5,
      distanceKm: 1447,
      avgSpeedKmph: 84.6,
      rakeDetails: 'LHB',
      otherDetails: 'Fully AC train',
      scrapedAt: Date.now(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    },
    route: [
      {
        id: 1,
        sequence: 1,
        stationCode: 'NDLS',
        stationName: 'New Delhi',
        isHalt: 1,
        scheduledArrival: 0,
        scheduledDeparture: 1010,
        haltDurationMinutes: 0,
        platform: '10',
        day: 1,
        distanceFromSourceKm: 0,
        speedOnSectionKmph: 0,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
      {
        id: 2,
        sequence: 2,
        stationCode: 'CNB',
        stationName: 'Kanpur Central',
        isHalt: 1,
        scheduledArrival: 1510,
        scheduledDeparture: 1515,
        haltDurationMinutes: 5,
        platform: '1',
        day: 1,
        distanceFromSourceKm: 441,
        speedOnSectionKmph: 110,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
      {
        id: 3,
        sequence: 3,
        stationCode: 'HWH',
        stationName: 'Howrah Jn',
        isHalt: 1,
        scheduledArrival: 315,
        scheduledDeparture: 0,
        haltDurationMinutes: 0,
        platform: '9',
        day: 2,
        distanceFromSourceKm: 1447,
        speedOnSectionKmph: 0,
        trackTypeId: 1,
        actualArrivalTime: null,
        actualDepartureTime: null,
        arrivalDelaySeconds: null,
        departureDelaySeconds: null,
        livePlatform: null,
        liveDistanceKm: null,
      },
    ],
    liveData: null,
    metadata: {
      hasLiveData: false,
      lastStaticUpdate: new Date().toISOString(),
      lastLiveUpdate: null,
      canRefreshLive: false,
      journeyStatus: {
        status: 'NOT_STARTED',
        journeyDate: '2026-01-14',
        canFetchLiveData: false,
        startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        endTime: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      },
    },
  },
};

export function getMockTrainData(trainNumber: string): TrainApiResponse | null {
  return MOCK_TRAIN_DATA[trainNumber] || null;
}

